---
resources:

# Git repos
- name: docker-concourse-git
  type: git
  source:
    uri: https://github.com/skyscrapers/docker-concourse.git
    branch: master

# Docker images
- name: concourse-concourse-image
  type: docker-image
  source:
    repository: concourse/concourse
- name: skyscrapers-concourse-image
  type: docker-image
  source:
    repository: skyscrapers/concourse
    username: {{DOCKER_HUB_USERNAME}}
    password: {{DOCKER_HUB_PASSWORD}}


jobs:

- name: build-concourse-image
  plan:
  - do:
    - get: docker-concourse-git
      trigger: true
    - get: concourse-concourse-image
      params: {save: true}
      trigger: true
    - task: get-concourse-version
      image: concourse-concourse-image
      config:
        platform: linux
        outputs:
          - name: output
        run:
          path: sh
          args:
            - -c
            - |
              concourse web --version > output/version
    - put: skyscrapers-concourse-image
      params:
        build: docker-concourse-git
        load: concourse-concourse-image
        tag: output/version
        tag_as_latest: true
